package com.roadgovern.hbm;

// Generated Dec 15, 2013 12:26:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer cityId;
	private District district;
	private String cityName;
	private Set<IssuePoc> issuePocs = new HashSet<IssuePoc>(0);
	private Set<Road> roads = new HashSet<Road>(0);

	public City() {
	}

	public City(District district, String cityName) {
		this.district = district;
		this.cityName = cityName;
	}

	public City(District district, String cityName, Set<IssuePoc> issuePocs,
			Set<Road> roads) {
		this.district = district;
		this.cityName = cityName;
		this.issuePocs = issuePocs;
		this.roads = roads;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public Set<IssuePoc> getIssuePocs() {
		return this.issuePocs;
	}

	public void setIssuePocs(Set<IssuePoc> issuePocs) {
		this.issuePocs = issuePocs;
	}

	public Set<Road> getRoads() {
		return this.roads;
	}

	public void setRoads(Set<Road> roads) {
		this.roads = roads;
	}

}
