package com.roadgovern.hbm;

// Generated Dec 15, 2013 12:26:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * District generated by hbm2java
 */
public class District implements java.io.Serializable {

	private Integer districtId;
	private State state;
	private String districtName;
	private Set<City> cities = new HashSet<City>(0);

	public District() {
	}

	public District(State state, String districtName) {
		this.state = state;
		this.districtName = districtName;
	}

	public District(State state, String districtName, Set<City> cities) {
		this.state = state;
		this.districtName = districtName;
		this.cities = cities;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
