package com.roadgovern.hbm;

// Generated Dec 15, 2013 12:26:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * IssuePoc generated by hbm2java
 */
public class IssuePoc implements java.io.Serializable {

	private IssuePocId id;
	private Users users;
	private IssueType issueType;
	private City city;

	public IssuePoc() {
	}

	public IssuePoc(IssuePocId id, Users users, IssueType issueType, City city) {
		this.id = id;
		this.users = users;
		this.issueType = issueType;
		this.city = city;
	}

	public IssuePocId getId() {
		return this.id;
	}

	public void setId(IssuePocId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public IssueType getIssueType() {
		return this.issueType;
	}

	public void setIssueType(IssueType issueType) {
		this.issueType = issueType;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

}
