package com.roadgovern.hbm;

// Generated Dec 15, 2013 12:26:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * IssueType generated by hbm2java
 */
public class IssueType implements java.io.Serializable {

	private Integer issueTypeId;
	private String issueTypeDesc;
	private Set<IssuePoc> issuePocs = new HashSet<IssuePoc>(0);

	public IssueType() {
	}

	public IssueType(String issueTypeDesc) {
		this.issueTypeDesc = issueTypeDesc;
	}

	public IssueType(String issueTypeDesc, Set<IssuePoc> issuePocs) {
		this.issueTypeDesc = issueTypeDesc;
		this.issuePocs = issuePocs;
	}

	public Integer getIssueTypeId() {
		return this.issueTypeId;
	}

	public void setIssueTypeId(Integer issueTypeId) {
		this.issueTypeId = issueTypeId;
	}

	public String getIssueTypeDesc() {
		return this.issueTypeDesc;
	}

	public void setIssueTypeDesc(String issueTypeDesc) {
		this.issueTypeDesc = issueTypeDesc;
	}

	public Set<IssuePoc> getIssuePocs() {
		return this.issuePocs;
	}

	public void setIssuePocs(Set<IssuePoc> issuePocs) {
		this.issuePocs = issuePocs;
	}

}
