package com.roadgovern.hbm;

// Generated Dec 15, 2013 12:26:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Items generated by hbm2java
 */
public class Items implements java.io.Serializable {

	private Integer itemId;
	private String itemDesc;
	private String itemCreatedBy;
	private Date createTs;
	private Date lastChangeTs;
	private boolean itemStatus;
	private String priority;
	private int stateId;
	private int districtId;
	private int cityId;
	private int roadId;
	private int issueTypeId;
	private String createdbyFirstName;
	private String createdbyLastName;
	private String createdbyAddress1;
	private String createdbyAddress2;
	private String createdbyCity;
	private String createdbyState;
	private String createdbyZip;
	private String createdbyPhone;
	private String createdbyEmail;
	private Set<ItemLog> itemLogs = new HashSet<ItemLog>(0);

	public Items() {
	}

	public Items(String itemCreatedBy, Date createTs, Date lastChangeTs,
			boolean itemStatus, int stateId, int districtId, int cityId,
			int roadId, int issueTypeId, String createdbyFirstName,
			String createdbyPhone) {
		this.itemCreatedBy = itemCreatedBy;
		this.createTs = createTs;
		this.lastChangeTs = lastChangeTs;
		this.itemStatus = itemStatus;
		this.stateId = stateId;
		this.districtId = districtId;
		this.cityId = cityId;
		this.roadId = roadId;
		this.issueTypeId = issueTypeId;
		this.createdbyFirstName = createdbyFirstName;
		this.createdbyPhone = createdbyPhone;
	}

	public Items(String itemDesc, String itemCreatedBy, Date createTs,
			Date lastChangeTs, boolean itemStatus, String priority,
			int stateId, int districtId, int cityId, int roadId,
			int issueTypeId, String createdbyFirstName,
			String createdbyLastName, String createdbyAddress1,
			String createdbyAddress2, String createdbyCity,
			String createdbyState, String createdbyZip, String createdbyPhone,
			String createdbyEmail, Set<ItemLog> itemLogs) {
		this.itemDesc = itemDesc;
		this.itemCreatedBy = itemCreatedBy;
		this.createTs = createTs;
		this.lastChangeTs = lastChangeTs;
		this.itemStatus = itemStatus;
		this.priority = priority;
		this.stateId = stateId;
		this.districtId = districtId;
		this.cityId = cityId;
		this.roadId = roadId;
		this.issueTypeId = issueTypeId;
		this.createdbyFirstName = createdbyFirstName;
		this.createdbyLastName = createdbyLastName;
		this.createdbyAddress1 = createdbyAddress1;
		this.createdbyAddress2 = createdbyAddress2;
		this.createdbyCity = createdbyCity;
		this.createdbyState = createdbyState;
		this.createdbyZip = createdbyZip;
		this.createdbyPhone = createdbyPhone;
		this.createdbyEmail = createdbyEmail;
		this.itemLogs = itemLogs;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	public String getItemCreatedBy() {
		return this.itemCreatedBy;
	}

	public void setItemCreatedBy(String itemCreatedBy) {
		this.itemCreatedBy = itemCreatedBy;
	}

	public Date getCreateTs() {
		return this.createTs;
	}

	public void setCreateTs(Date createTs) {
		this.createTs = createTs;
	}

	public Date getLastChangeTs() {
		return this.lastChangeTs;
	}

	public void setLastChangeTs(Date lastChangeTs) {
		this.lastChangeTs = lastChangeTs;
	}

	public boolean isItemStatus() {
		return this.itemStatus;
	}

	public void setItemStatus(boolean itemStatus) {
		this.itemStatus = itemStatus;
	}

	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public int getStateId() {
		return this.stateId;
	}

	public void setStateId(int stateId) {
		this.stateId = stateId;
	}

	public int getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(int districtId) {
		this.districtId = districtId;
	}

	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

	public int getRoadId() {
		return this.roadId;
	}

	public void setRoadId(int roadId) {
		this.roadId = roadId;
	}

	public int getIssueTypeId() {
		return this.issueTypeId;
	}

	public void setIssueTypeId(int issueTypeId) {
		this.issueTypeId = issueTypeId;
	}

	public String getCreatedbyFirstName() {
		return this.createdbyFirstName;
	}

	public void setCreatedbyFirstName(String createdbyFirstName) {
		this.createdbyFirstName = createdbyFirstName;
	}

	public String getCreatedbyLastName() {
		return this.createdbyLastName;
	}

	public void setCreatedbyLastName(String createdbyLastName) {
		this.createdbyLastName = createdbyLastName;
	}

	public String getCreatedbyAddress1() {
		return this.createdbyAddress1;
	}

	public void setCreatedbyAddress1(String createdbyAddress1) {
		this.createdbyAddress1 = createdbyAddress1;
	}

	public String getCreatedbyAddress2() {
		return this.createdbyAddress2;
	}

	public void setCreatedbyAddress2(String createdbyAddress2) {
		this.createdbyAddress2 = createdbyAddress2;
	}

	public String getCreatedbyCity() {
		return this.createdbyCity;
	}

	public void setCreatedbyCity(String createdbyCity) {
		this.createdbyCity = createdbyCity;
	}

	public String getCreatedbyState() {
		return this.createdbyState;
	}

	public void setCreatedbyState(String createdbyState) {
		this.createdbyState = createdbyState;
	}

	public String getCreatedbyZip() {
		return this.createdbyZip;
	}

	public void setCreatedbyZip(String createdbyZip) {
		this.createdbyZip = createdbyZip;
	}

	public String getCreatedbyPhone() {
		return this.createdbyPhone;
	}

	public void setCreatedbyPhone(String createdbyPhone) {
		this.createdbyPhone = createdbyPhone;
	}

	public String getCreatedbyEmail() {
		return this.createdbyEmail;
	}

	public void setCreatedbyEmail(String createdbyEmail) {
		this.createdbyEmail = createdbyEmail;
	}

	public Set<ItemLog> getItemLogs() {
		return this.itemLogs;
	}

	public void setItemLogs(Set<ItemLog> itemLogs) {
		this.itemLogs = itemLogs;
	}

}
