package com.roadgovern.hbm;

// Generated Dec 15, 2013 12:26:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItemLog generated by hbm2java
 */
public class ItemLog implements java.io.Serializable {

	private Integer logId;
	private Items items;
	private Status status;
	private String loggedBy;
	private String remarks;
	private Date createTs;
	private boolean displayFlag;
	private String assignedTo;
	private Set<ItemAttachments> itemAttachmentses = new HashSet<ItemAttachments>(
			0);

	public ItemLog() {
	}

	public ItemLog(Items items, String loggedBy, Date createTs,
			boolean displayFlag) {
		this.items = items;
		this.loggedBy = loggedBy;
		this.createTs = createTs;
		this.displayFlag = displayFlag;
	}

	public ItemLog(Items items, Status status, String loggedBy, String remarks,
			Date createTs, boolean displayFlag, String assignedTo,
			Set<ItemAttachments> itemAttachmentses) {
		this.items = items;
		this.status = status;
		this.loggedBy = loggedBy;
		this.remarks = remarks;
		this.createTs = createTs;
		this.displayFlag = displayFlag;
		this.assignedTo = assignedTo;
		this.itemAttachmentses = itemAttachmentses;
	}

	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public String getLoggedBy() {
		return this.loggedBy;
	}

	public void setLoggedBy(String loggedBy) {
		this.loggedBy = loggedBy;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Date getCreateTs() {
		return this.createTs;
	}

	public void setCreateTs(Date createTs) {
		this.createTs = createTs;
	}

	public boolean isDisplayFlag() {
		return this.displayFlag;
	}

	public void setDisplayFlag(boolean displayFlag) {
		this.displayFlag = displayFlag;
	}

	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	public Set<ItemAttachments> getItemAttachmentses() {
		return this.itemAttachmentses;
	}

	public void setItemAttachmentses(Set<ItemAttachments> itemAttachmentses) {
		this.itemAttachmentses = itemAttachmentses;
	}

}
