package com.roadgovern.hbm;

// Generated Dec 15, 2013 12:26:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * Road generated by hbm2java
 */
public class Road implements java.io.Serializable {

	private Integer roadId;
	private City city;
	private String roadType;
	private String roadName;
	private float roadWidth;
	private float roadLength;
	private String medianAvailable;
	private String pedestrianAvailable;
	private String streetLightAvailable;

	public Road() {
	}

	public Road(City city, String roadType, float roadWidth, float roadLength) {
		this.city = city;
		this.roadType = roadType;
		this.roadWidth = roadWidth;
		this.roadLength = roadLength;
	}

	public Road(City city, String roadType, String roadName, float roadWidth,
			float roadLength, String medianAvailable,
			String pedestrianAvailable, String streetLightAvailable) {
		this.city = city;
		this.roadType = roadType;
		this.roadName = roadName;
		this.roadWidth = roadWidth;
		this.roadLength = roadLength;
		this.medianAvailable = medianAvailable;
		this.pedestrianAvailable = pedestrianAvailable;
		this.streetLightAvailable = streetLightAvailable;
	}

	public Integer getRoadId() {
		return this.roadId;
	}

	public void setRoadId(Integer roadId) {
		this.roadId = roadId;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public String getRoadType() {
		return this.roadType;
	}

	public void setRoadType(String roadType) {
		this.roadType = roadType;
	}

	public String getRoadName() {
		return this.roadName;
	}

	public void setRoadName(String roadName) {
		this.roadName = roadName;
	}

	public float getRoadWidth() {
		return this.roadWidth;
	}

	public void setRoadWidth(float roadWidth) {
		this.roadWidth = roadWidth;
	}

	public float getRoadLength() {
		return this.roadLength;
	}

	public void setRoadLength(float roadLength) {
		this.roadLength = roadLength;
	}

	public String getMedianAvailable() {
		return this.medianAvailable;
	}

	public void setMedianAvailable(String medianAvailable) {
		this.medianAvailable = medianAvailable;
	}

	public String getPedestrianAvailable() {
		return this.pedestrianAvailable;
	}

	public void setPedestrianAvailable(String pedestrianAvailable) {
		this.pedestrianAvailable = pedestrianAvailable;
	}

	public String getStreetLightAvailable() {
		return this.streetLightAvailable;
	}

	public void setStreetLightAvailable(String streetLightAvailable) {
		this.streetLightAvailable = streetLightAvailable;
	}

}
