package com.roadgovern.hbm;

// Generated Dec 15, 2013 12:26:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private Integer statusId;
	private String statusName;
	private Set<ItemLog> itemLogs = new HashSet<ItemLog>(0);

	public Status() {
	}

	public Status(String statusName) {
		this.statusName = statusName;
	}

	public Status(String statusName, Set<ItemLog> itemLogs) {
		this.statusName = statusName;
		this.itemLogs = itemLogs;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public Set<ItemLog> getItemLogs() {
		return this.itemLogs;
	}

	public void setItemLogs(Set<ItemLog> itemLogs) {
		this.itemLogs = itemLogs;
	}

}
