package com.roadgovern.hbm;

// Generated Dec 15, 2013 12:26:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userId;
	private String firstName;
	private String lastName;
	private String role;
	private String password;
	private Date createTs;
	private String reportee;
	private String email;
	private String phone;
	private Set<IssuePoc> issuePocs = new HashSet<IssuePoc>(0);

	public Users() {
	}

	public Users(String userId, String firstName, String lastName, String role,
			String password, Date createTs) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.role = role;
		this.password = password;
		this.createTs = createTs;
	}

	public Users(String userId, String firstName, String lastName, String role,
			String password, Date createTs, String reportee, String email,
			String phone, Set<IssuePoc> issuePocs) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.role = role;
		this.password = password;
		this.createTs = createTs;
		this.reportee = reportee;
		this.email = email;
		this.phone = phone;
		this.issuePocs = issuePocs;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreateTs() {
		return this.createTs;
	}

	public void setCreateTs(Date createTs) {
		this.createTs = createTs;
	}

	public String getReportee() {
		return this.reportee;
	}

	public void setReportee(String reportee) {
		this.reportee = reportee;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set<IssuePoc> getIssuePocs() {
		return this.issuePocs;
	}

	public void setIssuePocs(Set<IssuePoc> issuePocs) {
		this.issuePocs = issuePocs;
	}

}
