package com.roadgovern.hbm;

// Generated Dec 14, 2013 2:14:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ward generated by hbm2java
 */
public class Ward implements java.io.Serializable {

	private Integer wardId;
	private int cityId;
	private int wardNo;
	private String wardName;

	public Ward() {
	}

	public Ward(int cityId, int wardNo) {
		this.cityId = cityId;
		this.wardNo = wardNo;
	}

	public Ward(int cityId, int wardNo, String wardName) {
		this.cityId = cityId;
		this.wardNo = wardNo;
		this.wardName = wardName;
	}

	public Integer getWardId() {
		return this.wardId;
	}

	public void setWardId(Integer wardId) {
		this.wardId = wardId;
	}

	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

	public int getWardNo() {
		return this.wardNo;
	}

	public void setWardNo(int wardNo) {
		this.wardNo = wardNo;
	}

	public String getWardName() {
		return this.wardName;
	}

	public void setWardName(String wardName) {
		this.wardName = wardName;
	}

}
